require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe DiseasesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Disease. As you add validations to Disease, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: Faker::Name.name, symptons: Faker::Name.name }
  }

  let(:invalid_attributes) {
    { name: '', symptons: Faker::Name.name }
  }

  # This should return the mi nimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DiseasesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before :each do
    # allow(controller).to receive(:valid_attributes).and_return(create(:disease))
    @disease = Disease.create!({ name: Faker::Name.name, symptons: Faker::Name.name })
  end

  describe "GET #index" do
    it "returns a success response" do
      Disease.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      disease = Disease.create! valid_attributes
      get :show, params: {id: disease.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      disease = Disease.create! valid_attributes
      get :edit, params: {id: disease.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Disease" do
        expect {
          post :create, params: {disease: valid_attributes}, session: valid_session
        }.to change(Disease, :count).by(1)
      end

      it "redirects to the created disease" do
        post :create, params: {disease: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Disease.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {disease: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {name: "#{valid_attributes[:name]}_update"}
      }

      it "updates the requested disease" do
        disease = Disease.create! valid_attributes
        put :update, params: {id: disease.to_param, disease: new_attributes}, session: valid_session
        disease.reload
        expect(response).to redirect_to(disease)
      end

      it "redirects to the disease" do
        disease = Disease.create! valid_attributes
        put :update, params: {id: disease.to_param, disease: valid_attributes}, session: valid_session
        expect(response).to redirect_to(disease)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        disease = Disease.create! valid_attributes
        put :update, params: {id: disease.to_param, disease: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested disease" do
      disease = Disease.create! valid_attributes
      expect {
        delete :destroy, params: {id: disease.to_param}, session: valid_session
      }.to change(Disease, :count).by(-1)
    end

    it "redirects to the diseases list" do
      disease = Disease.create! valid_attributes
      delete :destroy, params: {id: disease.to_param}, session: valid_session
      expect(response).to redirect_to(diseases_url)
    end
  end

  describe "#upload" do
    common_path = "#{Rails.root}/spec/factories"
    it "responds to html of upload_file" do
      disease_file_path = "#{common_path}/Diseases_blank_header.xlsx"
      post :upload, params:{ disease_file: disease_file_path, file_extention: '.xlsx' }
      expect(response).to redirect_to(upload_file_diseases_path)
    end

    it "responds to html of diseases_url" do
      disease_file_path = "#{common_path}/Diseases_new.xlsx"
      post :upload, params: { disease_file: disease_file_path, file_extention: '.xlsx' }
      expect(response).to redirect_to(diseases_url)
    end

    it "responds to xls error file" do
      disease_file_path = "#{common_path}/Diseases_invalid_data.xlsx"
      post :upload, params: { disease_file: disease_file_path, file_extention: '.xlsx' }
      expect(response.content_type).to eq "application/xls"
    end
  end
end
